#############
# host at http://flask-env.eba-varw8jnv.us-east-2.elasticbeanstalk.com/,
# also to http://drugexplorer.gehlenborglab.org
#############

branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: drug_server
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
#############
# host at drugexplorer.us-east-2.elasticbeanstalk.com
#############

# branch-defaults:
#   default:
#     environment: DrugServer2-env
#     group_suffix: null
# global:
#   application_name: drug_server_2
#   branch: null
#   default_ec2_keyname: null
#   default_platform: Python 3.7
