branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: drug-server
  branch: null
  default_ec2_keyname: Neo4j-AWS-EC2-Key
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: landingzone
  repository: null
  sc: null
  workspace_type: Application
